version: "3.9"

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8081:8081"
    networks:
      - app-tier  